### ISSUE TITLE
Usage with other packages

### ISSUE THREAD

**Issue by subdesign** [sboo/multiauth#24]
Any experience using Multiauth with zizaco/entrust or laravel/socialite ? I'm planning a project, should I consider issues with them?

**Comment by sboo** [comment]
I haven't looked at either of those packages, but it might get a bit rough with Socialite, I'd need to try it out. 

Entrust should work, because it doesn't directly bind into the Auth classes. I used another package as a base for my own solution in a recent project (where I implemented mutliauth), and that worked easily, because it is part of the User Model.
